name: Build and test NestJS project
on:
  push:
    branches:
      - dev/cicd
jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: read #This is required for actions/checkout
    steps:
    - name: Checkout
      uses: actions/checkout@v6.0.2
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v6.3.0
      with:
        # Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.
        node-version: 24.14.0 # Latest LTS (for now)

    - name: npm install, build and test
      env:
        DATABASE_URL: ${{ secrets.PRISMA_DATABASE_URL }}
      run: |
        npm install
        npx prisma generate
        npx nest build 
        npx jest
            
